apiVersion: v1
kind: Service
metadata:
  name: auth-service  # This is the DNS name other pods will use!
spec:
  selector:
    app: auth-service # This tells the Service: "Find Pods with this hashtag"
  ports:
    - protocol: TCP
      port: 3000      # The port other services use to talk to THIS service
      targetPort: 3000 # The actual port the Node.js app is listening on inside the Pod
  type: ClusterIP     # This means "Internal Only" (Hidden from the internet)