apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  # Internal URLs for Server-Side Rendering
  AUTH_SERVICE_URL: "http://auth-service:3000"
  GATEWAY_SERVICE_URL: "http://gateway-service:8000"
  METADATA_API_URL: "http://metadata-api-service:8001"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nextjs-app
        image: frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001
        envFrom:
        - configMapRef:
            name: frontend-config
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - port: 3001
      targetPort: 3001