apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce # One pod writes, but we can mount it to many!
  resources:
    requests:
      storage: 1Gi   # 1 Gigabyte is plenty for our images