apiVersion: v1
kind: ConfigMap
metadata:
  name: metadata-config
data:
  # Notice: we use metadata-db-service here!
  DATABASE_URL: "postgresql://postgres:super-secure-local-password-123@metadata-db-service:5432/metadata_db"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata-api
  template:
    metadata:
      labels:
        app: metadata-api
    spec:
      containers:
      - name: metadata-api
        image: metadata-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
        envFrom:
        - configMapRef:
            name: metadata-config
---
apiVersion: v1
kind: Service
metadata:
  name: metadata-api-service
spec:
  selector:
    app: metadata-api
  ports:
    - port: 8001
      targetPort: 8001